changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Improvements
      labels:
        - improvement
    - title: Bug Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'
