version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1m3w4a5wox1xg"
s3_prefix = "sam-app"
region = "ap-northeast-1"
profile = "serverless"
capabilities = "CAPABILITY_IAM"
image_repositories = []
